/**
 * Database types, mirroring `supabase/migrations/`.
 *
 * Hand-written rather than generated so the repo stays buildable without the
 * Supabase CLI. If you change a migration, change this file in the same commit —
 * `npm run typecheck` is what catches the two drifting apart at the call sites.
 */

export type TaskStatus = "todo" | "in-progress" | "done";
export type TaskPriority = "low" | "medium" | "high";
export type TaskKind = "assignment" | "reading" | "problem-set" | "project" | "lab-report" | "revision";
export type ExamKind = "midterm" | "final" | "quiz" | "practical" | "oral";
export type SessionKind = "lecture" | "lab" | "seminar" | "tutorial" | "study" | "exam";

/** Palette slot 1–5; see `src/lib/chart-palette.ts`. */
export type ColorSlot = 1 | 2 | 3 | 4 | 5;

type Timestamps = {
  created_at: string;
  updated_at: string;
};

export type Profile = Timestamps & {
  id: string;
  full_name: string | null;
  program: string | null;
  academic_year: string | null;
  term: string | null;
  daily_goal_minutes: number;
};

export type Course = Timestamps & {
  id: string;
  user_id: string;
  code: string;
  title: string;
  instructor: string | null;
  credits: number | null;
  location: string | null;
  color_slot: ColorSlot;
  grade: number | null;
  attendance: number | null;
  summary: string | null;
};

export type Topic = Timestamps & {
  id: string;
  user_id: string;
  course_id: string;
  title: string;
  position: number;
  is_complete: boolean;
};

export type Lecture = Timestamps & {
  id: string;
  user_id: string;
  course_id: string;
  title: string;
  lecture_date: string | null;
  position: number;
  notes: string | null;
};

export type Task = Timestamps & {
  id: string;
  user_id: string;
  course_id: string | null;
  title: string;
  kind: TaskKind;
  status: TaskStatus;
  priority: TaskPriority;
  due_date: string | null;
  estimate_minutes: number | null;
  checklist_done: number;
  checklist_total: number;
  completed_at: string | null;
};

export type Exam = Timestamps & {
  id: string;
  user_id: string;
  course_id: string | null;
  title: string;
  kind: ExamKind;
  exam_date: string;
  start_time: string | null;
  end_time: string | null;
  location: string | null;
  weight: number | null;
  preparation: number;
  topics: string[];
  notes: string | null;
};

export type Note = Timestamps & {
  id: string;
  user_id: string;
  course_id: string | null;
  topic_id: string | null;
  title: string;
  content: string;
  tags: string[];
  is_pinned: boolean;
};

export type ScheduleEvent = Timestamps & {
  id: string;
  user_id: string;
  course_id: string | null;
  title: string;
  kind: SessionKind;
  event_date: string;
  start_time: string;
  end_time: string;
  location: string | null;
  note: string | null;
};

export type StudySession = {
  id: string;
  user_id: string;
  course_id: string | null;
  started_at: string;
  /** `null` while the timer is still running. */
  ended_at: string | null;
  /** Generated by Postgres; `null` while running. */
  duration_minutes: number | null;
  focus: number | null;
  note: string | null;
  created_at: string;
};

/** Columns the database fills in itself and clients must never send. */
type Managed = "id" | "user_id" | "created_at" | "updated_at";

/** An insert payload: everything except what the database owns. */
export type Insert<T> = Omit<T, Managed>;
/** An update payload: any subset of the writable columns. */
export type Update<T> = Partial<Insert<T>>;

type TableShape<Row, I, U> = {
  Row: Row;
  Insert: I;
  Update: U;
  /** supabase-js requires this key even when no relationships are declared. */
  Relationships: [];
};

export type Database = {
  public: {
    Tables: {
      profiles: TableShape<Profile, Partial<Profile> & { id: string }, Partial<Profile>>;
      courses: TableShape<Course, Insert<Course> & { user_id: string }, Update<Course>>;
      topics: TableShape<Topic, Insert<Topic> & { user_id: string }, Update<Topic>>;
      lectures: TableShape<Lecture, Insert<Lecture> & { user_id: string }, Update<Lecture>>;
      tasks: TableShape<Task, Insert<Task> & { user_id: string }, Update<Task>>;
      exams: TableShape<Exam, Insert<Exam> & { user_id: string }, Update<Exam>>;
      notes: TableShape<Note, Insert<Note> & { user_id: string }, Update<Note>>;
      schedule_events: TableShape<ScheduleEvent, Insert<ScheduleEvent> & { user_id: string }, Update<ScheduleEvent>>;
      study_sessions: TableShape<
        StudySession,
        Omit<StudySession, "id" | "user_id" | "created_at" | "duration_minutes"> & { user_id: string },
        Partial<Omit<StudySession, "id" | "user_id" | "created_at" | "duration_minutes">>
      >;
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
    Enums: {
      task_status: TaskStatus;
      task_priority: TaskPriority;
      task_kind: TaskKind;
      exam_kind: ExamKind;
      session_kind: SessionKind;
    };
  };
}
